### ISSUE TITLE
Compatibility with Laravel 9

### ISSUE THREAD

**Issue by kolaente** [felixdorn/laravel-rickroll#14]
I know, I know. Laravel 9 was just released today, it would be great if this package would support it!

**Comment by felixdorn** [comment]
I've just released a new version for L9, let me know if you encounter any issues (ping me on this thread).

Have a nice day!

**Comment by kolaente** [comment]
Great! I was able to install this in my Laravel 9 project. However, it looks like the routes are not registered anymore. Visiting one of them gives me a 404.

Checking with a `dd($this->urls);` in the `__destruct` method of the class, where the routes are registered gives me an empty array.

I installed it like this in my `web.php` file:

```php
RickRoll::routes();
```

**Comment by felixdorn** [comment]
@kolaente I've released 1.1.1.

**Comment by kolaente** [comment]
That works great. Thank you!
